name: Deploy Dev Version of Vue App to S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Use .env.development
        run: cp .env.development .env

      - name: Verify .env file
        run: cat .env

      - name: Build Vue App
        run: npm run build -- --mode development

      - name: Configure AWS CLI Manually
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = eu-west-1" >> ~/.aws/config

      - name: Sync Build Files to S3
        run: aws s3 sync ./dist s3://dev-ledgefast --delete
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E1P0RBSL1DLD1F --paths "/*"
        env:
          AWS_REGION: eu-west-1
